### ISSUE TITLE
Help, i'm an idiot!

### ISSUE THREAD

**Issue by jsheltz** [bachittle/playlist-creator#4]
Hoping you might be able to shed some light on what I'm missing here, as i have virtually no python experience. 

I've managed to successfully generate the list of links as a .dat file with discord_scraper but when I go to run youtube_scraper I'm getting a missing file directory  error for songs.json. Here's the error:

Please enter the name of the song file you would like to load. (Default is songs.dat):
Traceback (most recent call last):
  File "C:\Users\jshel\Desktop\playlist-creator-master\scrapers\youtube_scraper.py", line 18, in <module>
    file_in = open("songs.json", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'songs.json'

I'm sure i'm missing something simple but any advice would be greatly appreciated!

**Comment by bachittle** [comment]
It's a bug on my part, wrote this code a while back and I guess I missed it. That part of the code checks if there is already an existing songs.json file to work with, if you make an empty songs.json file with just {} it should work as intended.

**Comment by jsheltz** [comment]
Awesome, that got me past it. Thanks man!
